services:
  postgres:
    image: postgres:12.22
    container_name: TTECH_postgres
    restart: "no"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ttech
    ports:
      - 5432:5432
    volumes:
      - TTECH_postgres_data:/var/lib/postgresql/data
    networks:
      - TTECH_network

  redis:
    image: redis:8.0.2
    container_name: TTECH_redis
    restart: "no"
    ports:
      - 6379:6379
    volumes:
      - TTECH_redis_data:/data
    networks:
      - TTECH_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: TTECH_zookeeper
    restart: "no"
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - TTECH_network

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: TTECH_kafka
    restart: "no"
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: TTECH_zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - TTECH_network

volumes:
  TTECH_postgres_data:
  TTECH_redis_data:

networks:
  TTECH_network:
    driver: bridge

## Docker Compose ##

# docker compose version

# cd devops
# docker compose -p deal up -d
# docker compose -p deal down
# docker compose -p deal start
# docker compose -p deal stop

# docker compose -f devops/docker-compose.yml -p deal up -d
# docker compose -f devops/docker-compose.yml -p deal down

# docker compose -p deal up -d db-redis
# docker compose -p deal down db-redis
# docker compose -p deal rm -s -f db-redis

# NOTE: Docker Compose
# -p <project-name>: đặt tên và tìm đến project-name
# -f <file-name>: tìm đến file docker-compose không theo mặc định
# -d (--detach): run at background mode, don't log, return prompt
# -s (--stop): stop before delete
# -f (--force): force delete without confirming
# up, down, rm: commands managed by Docker Compose

## Docker Engine ##

# docker ps
# docker ps -a
# docker volume ls
# docker network ls

# docker start postgres-12.22
# docker stop postgres-12.22

# NOTE: Docker Engine
# start, stop: commands managed by Docker Engine
# ps (process status): list running containers
# ps -a (all): list all container
# exec: để thực thi một lệnh bên trong môi trường một container đang chạy.
# -it: lệnh kết hợp -i & -t
# -i (interactive): giữ cho luồng input (bàn phím) mở => nhập lệnh.
# -t (tty): tạo ra một terminal giả lập (có màu sắc, để nạn tương tác, gõ lệnh thoải mái).

## REDIS ##

# Pull db-redis:
# - Image db-redis
# - Network deal_deal-network
# - Volume deal_redis-data
# - Container deal-db-redis-1

# Test db-redis:
# docker exec -it deal-db-redis-1 redis-cli: mở Redis client
# PING => PONG
# KEYS *
# SET user:1 "Dino" => OK
# GET user:1 => "Dino"
# SET user:1 "TN" => OK
# GET user:1 => "TN"
# DEL user:1 => (integer) 1
# GET user:1 => (nil)
# QUIT