# demo

server:
  port: 8080

spring:
  application:
    name: backend
  datasource:
    url: "jdbc:postgresql://localhost:5433/deal" #STRICT
    username: postgres
    password: 123456
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update #Hibernate ddl auto options: update, create, drop, create-drop, validate, none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # dialect: org.hibernate.dialect.PostgreSQLDialect
        # jdbc.lob.non_contextual_creation: true #doesn't use sessions to persist effectively
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    org.springframework.security: DEBUG

media:
  uri: "file:///D:/.Project/kltn/DEAL/server/files" #STRICT

jwt:
  access:
    secret-key: "" #base64 64 bytes
    valid-duration: 1 #days
  refresh:
    secret-key: "" #hex 64 bytes
    valid-duration: 7 #days

oauth2:
  google:
    client-id: "" #STRICT
    client-secret: "" #STRICT
    redirect-uri: "" #STRICT
    grant-type: "authorization_code"

